name: C/C++ CI

on:
  push:
    branches: [ main, staticCodeAnalysis ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install Qt
      uses: jurplel/install-qt-action@v2
    - name: cmake
      run: cmake .
    - name: make all targets
      run: make all

    - name: UT for BtsApplication
      run: make BtsApplicationUT 

    - name: run BTS ut
      run: ./BTS/Tests/Application/BtsApplicationUT

    - name: UT for COMMON
      run: make COMMON_UT

    - name: run COMMON ut
      run: ./COMMON/Tests/COMMON_UT

    - name: UT for UeApplication
      run: make UeApplicationUT

    - name: run UeApplication ut
      run: ./UE/Tests/Application/UeApplicationUT

    - name: Install cppcheck
      run: sudo apt-get -y install cppcheck

    - name: run cppcheck
      run: cppcheck UE -i UE/Tests